stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build crypto:
  stage: build
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    paths:
      - build/libs
  script:
    - ./gradlew assemble

test crypto:
  stage: test
  script:
    - ./gradlew check

deploy crypto:
  stage: deploy
  only:
    refs:
      - main
  script:
    - ssh ec2-user@cryptocalc.ml "cd ~/ics0024-2021-part1 && git pull origin main && ./gradlew assemble && sudo docker-compose down && sudo docker-compose up -d --build && exit"
