stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build crypto:
  stage: build
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    paths:
      - build/libs
#  tags:
#    - crypto
  script:
    - ./gradlew assemble

test crypto:
  stage: test
#  tags:
#    - crypto
  script:
    - ./gradlew check

deploy crypto:
  stage: deploy
  only:
    refs:
      - main
 # tags:
 #   - crypto
  script:
    - ssh ec2-user@cryptocalc.ml "cd ~/ics0024-2021-part1 && git pull origin main && exit"
#    - mkdir -p ~/api-deployment # mkdir make folder api-deployment ~/ is under current user directory so for gitlab it would be /home/gitlab/api-deployment
#    - rm -rf ~/api-deployment/* # rm remove -rf is recursive files from api-deployment
#    - cp -r build/libs/. ~/api-deployment # cp - copy build/libs is where
#    - sudo service crypto restart  # this requires sudo rights for gitlab user
