---
- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: restart prometheus
  service:
    name: prometheus
    state: restarted

- name: Systemctl daemon-reload
  shell: "systemctl daemon-reload"

- name: Restart prometheus
  service:
    name: prometheus
    state: restarted
