---
- name: Add the user 'prometheus' with a specific uid and a primary group of 'admin'
  user:
    name: prometheus
    comment: prometheus user
    create_home: no

- name: create /etc/prometheus directory
  file:
    path: /etc/prometheus
    state: directory
    owner: prometheus
    group: prometheus

- name: create /var/lib/prometheus directory
  file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus

- name: download prometheus
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.31.1/prometheus-2.31.1.linux-amd64.tar.gz
    dest: /usr/local/bin/
    copy: no

- name: Creates directory
  file:
    path: /srv/prometheus
    state: directory

- name: Copy file prometheus-2.31.1.linux-amd64/prometheus to /usr/local/bin
  copy:
    src: /usr/local/bin/prometheus-2.31.1.linux-amd64/prometheus
    dest: /usr/local/bin
    remote_src: yes

- name: Copy file prometheus-2.31.1.linux-amd64/promtool to /usr/local/bin/
  copy:
    src: /usr/local/bin/prometheus-2.31.1.linux-amd64/promtool
    dest: /usr/local/bin
    remote_src: yes

- name: Copy file prometheus-2.31.1.linux-amd64/console to /etc/prometheus
  copy:
    src: /usr/local/bin/prometheus-2.31.1.linux-amd64/consoles
    dest: /etc/prometheus/
    remote_src: yes

- name: Copy file prometheus-2.31.1.linux-amd64/console_libraries to /etc/prometheus
  copy:
    src: /usr/local/bin/prometheus-2.31.1.linux-amd64/console_libraries
    dest: /etc/prometheus/
    remote_src: yes

- name: Remove prometheus-2.31.1.linux-amd64.tar.gz
  file:
    path: /usr/local/bin/prometheus-2.31.1.linux-amd64.tar.gz
    state: absent

- name: Remove prometheus-2.31.1.linux-amd64
  file:
    path: /usr/local/bin/prometheus-2.31.1.linux-amd64
    state: absent

- name: Ansible set owner permission for files
  file:
    path: "{{ item }}"
    owner: prometheus
    group: prometheus
    state: file
  with_items:
    - /usr/local/bin/prometheus
    - /usr/local/bin/promtool

- name: Ansible set owner permission for directoris
  file:
    path: "{{ item }}"
    owner: prometheus
    group: prometheus
    state: directory
    recurse: yes
  with_items:
    - /etc/prometheus
    - /etc/prometheus/consoles
    - /etc/prometheus/console_libraries
    - /var/lib/prometheus

- name: Downloading yml file
  template:
    src: myPrometheus.yml
    dest: /etc/prometheus/prometheus.yml
    mode: 0755

- name: Downloading service file
  template:
    src: myPrometheus.service
    dest: /etc/systemd/system/prometheus.service
    mode: 0755

- name: Servisizing prometheus
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify:
    - Systemctl daemon-reload
    - Restart prometheus

- name: Prometheus enabled and started
  service:
    name: prometheus
    state: started
    enabled: yes
