---
- hosts: all
  gather_facts: yes
  tasks:
    - debug: var=ansible_default_ipv4 verbosity=0

- name: prometheus
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - prometheus
    - nginx_exporter
    - node_exporter
    - docker_exporter